### ISSUE TITLE
Getting error in the python job

### ISSUE THREAD

**Issue by JyotinP** [airscholar/SparkingFlow#1]
{base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
{spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master-1:7077 --name arrow-spark jobs/python/wordcountjob.py
{spark_submit.py:521} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
{spark_submit.py:521} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-arm64/bin/java: No such file or directory
{spark_submit.py:521} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
{taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master-1:7077 --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.

**Comment by franceZa** [comment]
at Dockerfile add " RUN export JAVA_HOME" It works for me

Set JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME

**Comment by weldermartins** [comment]
> at Dockerfile add " RUN export JAVA_HOME" It works for me
> 
> Set JAVA_HOME environment variable ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/ RUN export JAVA_HOME

I did as you advised, but in my case I still got the same error.

[2024-01-16, 20:01:50 UTC] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task python_job (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 239)

![image](https://github.com/airscholar/SparkingFlow/assets/7424153/5a931731-971b-4023-911f-2bad4b962b5d)

**python and java compatible**
![image](https://github.com/airscholar/SparkingFlow/assets/7424153/c90f7294-e479-41e5-83d5-0fa32a16c622)


**Versions**
![image](https://github.com/airscholar/SparkingFlow/assets/7424153/28414abe-be63-4cda-9e21-aeacd747f785)

**variables**
![image](https://github.com/airscholar/SparkingFlow/assets/7424153/e71cf4cd-09d4-4395-8841-963c7fa32b0d)

**docker-compose.yml**
![image](https://github.com/airscholar/SparkingFlow/assets/7424153/759d159b-87df-452d-9af5-261ea7d25aa9)


**Airflow connection**
![image](https://github.com/airscholar/SparkingFlow/assets/7424153/f9e0ac5f-842c-437e-b736-caa9927a3b23)

** Airflow Job Error**
![image](https://github.com/airscholar/SparkingFlow/assets/7424153/d366d249-4658-4fd8-8e42-76e3bf4a3c77)

**On my machine local, spark-submit ran without errors.**
![image](https://github.com/airscholar/SparkingFlow/assets/7424153/e9d2c562-3a82-402a-a209-e6c3004811ea)

**Comment by yashraizb** [comment]
@weldermartins Please check this issue [link](https://github.com/airscholar/SparkingFlow/issues/7) since this worked for me. And let me if this works for you.

**Comment by yashraizb** [comment]
@JyotinP It looks like ps command is not found, try adding procps in the dockerfile where java sdk and other packages are getting installed. Refer the below code:

RUN apt-get update && \
    apt-get install -y gcc python3-dev openjdk-11-jdk **procps** && \
    apt-get clean
