### ISSUE TITLE
/usr/lib/jvm/java-11-openjdk-arm64/bin/java: No such file or directory

### ISSUE THREAD

**Issue by yashraizb** [airscholar/SparkingFlow#7]
Whenever i run the spark python job, it is failing with this error message which I found in logs

Full error trace:

 Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow.python_job manual__2024-08-04T09:59:23.381699+00:00 [queued]>
[2024-08-04, 09:59:27 UTC] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow.python_job manual__2024-08-04T09:59:23.381699+00:00 [queued]>
[2024-08-04, 09:59:27 UTC] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-04, 09:59:27 UTC] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-08-04 09:59:23.381699+00:00
[2024-08-04, 09:59:27 UTC] {standard_task_runner.py:57} INFO - Started process 313 to run task
[2024-08-04, 09:59:27 UTC] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_***', 'python_job', 'manual__2024-08-04T09:59:23.381699+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpqfvzkk78']
[2024-08-04, 09:59:27 UTC] {standard_task_runner.py:85} INFO - Job 5: Subtask python_job
[2024-08-04, 09:59:27 UTC] {task_command.py:415} INFO - Running <TaskInstance: spark_airflow.python_job manual__2024-08-04T09:59:23.381699+00:00 [running]> on host 8bec8901d049
[2024-08-04, 09:59:27 UTC] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_***' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T09:59:23.381699+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T09:59:23.381699+00:00'
[2024-08-04, 09:59:27 UTC] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-08-04, 09:59:27 UTC] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2024-08-04, 09:59:27 UTC] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-arm64/bin/java: No such file or directory
[2024-08-04, 09:59:27 UTC] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2024-08-04, 09:59:27 UTC] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2024-08-04, 09:59:27 UTC] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=spark_***, task_id=python_job, execution_date=20240804T095923, start_date=20240804T095927, end_date=20240804T095927
[2024-08-04, 09:59:27 UTC] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task python_job (Cannot execute: spark-submit --master spark://spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 313)
[2024-08-04, 09:59:27 UTC] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-04, 09:59:27 UTC] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check

**Comment by yashraizb** [comment]
Resolved it.

the dockerfile's JAVA_HOME environment variable is not set correctly. Upon making the change the dockerfile from 

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-arm64   -->   ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

**from arm64 to amd64** it started working.
